#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-HTML-TableExtract
Version  : 2.15
Release  : 1
URL      : https://cpan.metacpan.org/authors/id/M/MS/MSISK/HTML-TableExtract-2.15.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/M/MS/MSISK/HTML-TableExtract-2.15.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libh/libhtml-tableextract-perl/libhtml-tableextract-perl_2.15-1.debian.tar.xz
Summary  : unknown
Group    : Development/Tools
License  : GPL-1.0
Requires: perl-HTML-TableExtract-license
Requires: perl-HTML-TableExtract-man
BuildRequires : perl(HTML::Parser)

%description
HTML-TableExtract
-----------------
HTML::TableExtract is a module that simplifies the extraction of
information contained in tables within HTML documents.

%package license
Summary: license components for the perl-HTML-TableExtract package.
Group: Default

%description license
license components for the perl-HTML-TableExtract package.


%package man
Summary: man components for the perl-HTML-TableExtract package.
Group: Default

%description man
man components for the perl-HTML-TableExtract package.


%prep
tar -xf %{SOURCE1}
cd ..
%setup -q -n HTML-TableExtract-2.15
mkdir -p %{_topdir}/BUILD/HTML-TableExtract-2.15/deblicense/
mv %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/HTML-TableExtract-2.15/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/perl-HTML-TableExtract
cp LICENSE %{buildroot}/usr/share/doc/perl-HTML-TableExtract/LICENSE
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/HTML/TableExtract.pm

%files license
%defattr(-,root,root,-)
/usr/share/doc/perl-HTML-TableExtract/LICENSE

%files man
%defattr(-,root,root,-)
/usr/share/man/man3/HTML::TableExtract.3
